version: "3"

services:

  # web
  web:
    image: node:current-alpine
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./services/web:/usr/src/app
    command: [sh, -c, npm i && npm run dev]
    ports:
      - 3000:3000

  # app
  app:
    image: node:current-alpine
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./services/app:/usr/src/app
    command: [sh, -c, npm i && npm run start]
    ports:
      - 3001:3001