version: "3"

services:
  # web
  web:
    image: node:current-alpine
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./services/web:/usr/src/app
    command: [sh, -c, npm i && npm run dev]
    ports:
      - 3000:3000

  # app
  app:
    image: node:current-alpine
    working_dir: /usr/src/app
    tty: true
    volumes:
      - ./services/app:/usr/src/app
    command: [sh, -c, npm i && npm run start]
    ports:
      - 3001:3001

  # postgre
  postgre:
    image: postgres:14.4-bullseye
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
      TZ: "Asia/Tokyo"
    volumes:
      - ./services/postgre/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # adminer
  adminer:
    image: adminer:4.8.1
    ports:
      - 5433:8080
